### ISSUE TITLE
Example of UI error

### ISSUE THREAD

**Issue by Ekultek** [bytecode77/living-off-the-land#2]
Would you be kind enough to show an example of the UI issues in regedit from the null byte key?

**Comment by bytecode77** [comment]
You can just run LivingOffTheLand.exe to install it. Then, go to the registry Run\ key as seen on the screenshot. You will see the error message from RegEdit caused by the null embedded character.

When you run Uninstall.exe, both registry values are removed, which is a complete uninstallation. RegEdit will display the Run\ key normally again.

**Comment by Ekultek** [comment]
@bytecode77 i found one online also, thank you i appreciate your time. (I totally forgot I made this issue lol)
